# -*- coding: utf-8 -*-
from datetime import datetime
from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError
from .fleet_api import FleetAPIClient


class ResUsers(models.Model):
    _inherit = 'res.users'

    fleet_api_url = fields.Char(
        string='Fleet Platform URL',
        help='Fleet Control Room endpoint URL (e.g., http://127.0.0.1:8000 or https://150.129.62.169.nip.io:8000). Leave blank to use system default.',
    )
    fleet_personal_token = fields.Char(
        string='Fleet Personal Access Token',
        copy=False,
        help='Personal API Token or Operator Secret generated by the Fleet Platform.',
    )
    fleet_role = fields.Selection(
        selection=[
            ('viewer', 'Viewer (Read-Only)'),
            ('developer', 'Developer (Deploy, Staging, Backups)'),
            ('admin', 'Platform Administrator (Full Rights)'),
        ],
        string='Fleet Platform Role',
        readonly=True,
        copy=False,
        help='Resolved RBAC role on the fleet platform.',
    )
    fleet_username = fields.Char(
        string='Fleet Username',
        readonly=True,
        copy=False,
    )
    fleet_display_name = fields.Char(
        string='Fleet Operator Name',
        readonly=True,
        copy=False,
    )
    fleet_assigned_projects = fields.Char(
        string='Fleet Assigned Projects',
        readonly=True,
        copy=False,
        help='Projects accessible with this token (* for all projects).',
    )
    fleet_is_authenticated = fields.Boolean(
        string='Fleet Authenticated',
        readonly=True,
        default=False,
        copy=False,
    )
    fleet_last_verified = fields.Datetime(
        string='Last Verified At',
        readonly=True,
        copy=False,
    )

    def get_fleet_token(self) -> str:
        """Returns the user's personal token or falls back to the system master token."""
        self.ensure_one()
        if self.fleet_personal_token:
            return self.fleet_personal_token.strip()
        system_token = self.env['ir.config_parameter'].sudo().get_param('fleet.default_api_key', '')
        return (system_token or "").strip()

    def action_verify_fleet_token(self):
        """Verifies the personal token against the platform and syncs Odoo security groups."""
        self.ensure_one()
        token = (self.fleet_personal_token or '').strip()
        if not token:
            raise UserError(_("Please input your Personal Access Token before verifying."))

        base_url = self.fleet_api_url or self.env['ir.config_parameter'].sudo().get_param(
            'fleet.platform_url', 'http://127.0.0.1:8000'
        )

        client = FleetAPIClient(base_url=base_url, token=token)
        result = client.verify_token(token)

        if not result.get("ok"):
            self.write({
                'fleet_is_authenticated': False,
                'fleet_role': False,
            })
            raise UserError(_("Token Verification Failed:\n%s") % result.get("error", "Invalid token"))

        role = result.get("role", "viewer")
        user_info = result.get("user") or {}
        assigned = user_info.get("assigned_projects", ["*"])
        assigned_str = ", ".join(assigned) if isinstance(assigned, list) else str(assigned)

        self.write({
            'fleet_role': role,
            'fleet_username': user_info.get("username", ""),
            'fleet_display_name': user_info.get("display_name", ""),
            'fleet_assigned_projects': assigned_str,
            'fleet_is_authenticated': True,
            'fleet_last_verified': fields.Datetime.now(),
        })

        # Dynamically synchronize Odoo security group with resolved Fleet Role
        group_viewer = self.env.ref('fleet_connector.group_fleet_viewer', raise_if_not_found=False)
        group_dev = self.env.ref('fleet_connector.group_fleet_developer', raise_if_not_found=False)
        group_admin = self.env.ref('fleet_connector.group_fleet_admin', raise_if_not_found=False)

        groups_to_add = []
        if role == 'viewer' and group_viewer:
            groups_to_add.append(group_viewer.id)
        elif role == 'developer' and group_dev:
            groups_to_add.extend([group_viewer.id, group_dev.id] if group_viewer else [group_dev.id])
        elif role == 'admin' and group_admin:
            all_g = [g.id for g in [group_viewer, group_dev, group_admin] if g]
            groups_to_add.extend(all_g)

        if groups_to_add:
            self.sudo().write({'groups_id': [(4, gid) for gid in groups_to_add]})

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _("Fleet Token Verified"),
                'message': _("Successfully connected to Fleet Platform as '%s' with role '%s'. Rights updated.") % (
                    user_info.get("display_name") or user_info.get("username") or role,
                    role.upper(),
                ),
                'type': 'success',
                'sticky': False,
            }
        }
